mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portfolio/', include('portfolio.urls', namespace="portfolio")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import patterns, url

from portfolio import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<study_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<study_id>\d+)/ajax/$', views.detail_ajax, name='detail-ajax'),
    url(r'^(?P<study_id>\d+)/thankyou/$', views.comment_success, name='comment-success'),
    url(r'^(?P<study_id>\d+)/comments/$', views.get_comments_ajax, name='get-comments'),
)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Poll(models.Model):
    author = models.CharField(max_length=60)
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    answer = models.CharField(max_length=200)
    count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.answer

portfolio/models.py
from django.db import models

# Create your models here.
class CaseStudy(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    picture = models.ImageField(upload_to='photos/%Y/%m/%d')

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    message = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    casestudy = models.ForeignKey(CaseStudy)

    def __unicode__(self):
        return self.message

portfolio/forms.py
from django import forms

class CommentForm(forms.Form):
    message = forms.CharField(max_length=200)
    author = forms.CharField(max_length=200)

polls/views.py
# Create your views here.

portfolio/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core import serializers

from portfolio.models import CaseStudy, Comment
from portfolio.forms import CommentForm

def index(request):
    studies = CaseStudy.objects.all()
    context = {'studies' : studies}
    return render(request, 'portfolio/index.html', context)

def comment_success(request, study_id):
    study = get_object_or_404(CaseStudy, pk=study_id)

    context = {'study': study}
    return render(request, 'portfolio/comment_thankyou.html', context)


def detail(request, study_id):
    study = get_object_or_404(CaseStudy, pk=study_id)
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            c = Comment(message=cd.get('message'), author=cd.get('author'), casestudy=study)
            c.save()

            context = {
                'study': study,
                'form': comment_form,
            }
            return HttpResponseRedirect(reverse('portfolio:comment-success', args=(study_id,)))
        else:
            context = {
                'study': study,
                'form': comment_form,
                'error': 'Error with your form. Please fix.',
            }
            return render(request, 'portfolio/detail.html', context)
            

    comment_form = CommentForm()
    context = {
        'study' : study,
        'form' : comment_form,
    }
    return render(request, 'portfolio/detail.html', context)

def detail_ajax(request, study_id):
    study = get_object_or_404(CaseStudy, pk=study_id)
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            c = Comment(message=cd.get('message'), author=cd.get('author'), casestudy=study)
            c.save()

            context = {
                'study': study,
                'form': comment_form,
            }
            return HttpResponseRedirect(reverse('portfolio:comment-success', args=(study_id,)))
        else:
            context = {
                'study': study,
                'form': comment_form,
                'error': 'Error with your form. Please fix.',
            }
            return render(request, 'portfolio/detail_ajax.html', context)
            

    comment_form = CommentForm()
    context = {
        'study' : study,
        'form' : comment_form,
    }
    return render(request, 'portfolio/detail_ajax.html', context)

def get_comments_ajax(request, study_id):
    study = get_object_or_404(CaseStudy, pk=study_id)

    comments = serializers.serialize('json', Comment.objects.filter(casestudy=study), fields=('message', 'author', 'pub_date',))

    return HttpResponse(comments)

portfolio/templates/portfolio/base.html
{% load staticfiles %}
{% load thumbnail %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/portfolio.css' %}">
<title>{% block title %}Welcome to my portfolio{% endblock %}</title>
{% block extrascripts %}{% endblock %}
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

portfolio/templates/portfolio/comment_thankyou.html
{% extends 'portfolio/base.html' %}

{% block content %}

    {% if study %}
    <h1>Thank you for your comment</h1>
    <p>Return back to <a href="{% url 'portfolio:detail' study.id %}">{{ study }}</a></p>

    {% else %}
    <p>Whoa, how did you get here???</p>
    {% endif %}

{% endblock %}

portfolio/templates/portfolio/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

    {% if study %}
    <h1>{{ study.title }}</h1>
    <img src="{{ MEDIA_URL }}{{ study.picture }}" /><br/>
    <p>{{ study.description|safe }}</p>

    <form action="{% url 'portfolio:detail' study.id %}" method="POST" id="comment-form">
    <table>
    {% csrf_token %}
    {{ form }}
    </table>
    <button>Leave a comment</button>
    </form>


    {% else %}
    <p>No studies here, bud.</p>
    {% endif %}

{% endblock %}

portfolio/templates/portfolio/detail_ajax.html
{% extends 'portfolio/base.html' %}

{% block title %}{{ study.title }}{% endblock %}

{% block extrascripts %}
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>

<script>
$(function () {
    $('#comment-form').submit(
        function (evt) {
            alert ('Just tried to submit');
            // Don't really submit the form
            evt.preventDefault();

            $.ajax({
                url: $(this).attr('action'),
                type: 'post',
                data: $(this).serialize(),
                success: function (data) {
                    alert('Successfully posted your comment.');
                },
                error: function () {
                    alert('Can\'t post your comment.');
                },
            });

            return false;
        });
});
</script>

{% endblock %}

{% block content %}

    {% if study %}
    <h1 id="title">{{ study.title }} (ajax version)</h1>
    <img src="{{ MEDIA_URL }}{{ study.picture }}" /><br/>
    <p>{{ study.description|safe }}</p>

    <form action="{% url 'portfolio:detail' study.id %}" method="POST" id="comment-form">
    <table>
    {% csrf_token %}
    {{ form }}
    </table>
    <button>Leave a comment</button>
    </form>


    {% else %}
    <p>No studies here, bud.</p>
    {% endif %}

{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load portfolio_tags %}

{% block content %}
{% if studies %}
<ul>
    {% for study in studies %}
    <li>
       {% thumbnail study.picture "100x100" as pic %}
       <img src="{{ MEDIA_URL }}{{ pic.url }}" />
       {% empty %}
       [ No Image ]
       {% endthumbnail %}
       <a href="{% url 'portfolio:detail' study.id %}">{{ study.title }}</a>
    </li>
    {% endfor %}
</ul>

<h2>Images for our portfolio</h2>

{% portfolio_images %}


{% endif %}
{% endblock %}

portfolio/templates/portfolio/portfolio_images.html
<ul>
   {% for img in img_list %}
   <li>{{ img.url }}</li>
   {% endfor %}
</ul>